### ISSUE TITLE
Songs are grayed

### ISSUE THREAD

**Issue by SupLiCatinG** [AnanthVivekanand/spotify-adblock#52] opened 2021-12-09 19:09 UTC
![image](https://user-images.githubusercontent.com/94017480/145459961-52bbfd92-48b5-4fa5-91bb-5bb0a37bd0f3.png)

Still can play audio but cant select song 
I tried re-installing everything but still no luck

**Comment by maximko** [comment] 2021-12-10 11:40
Same for me, audio also stops after 6 seconds of playing. I think it began yesterday or day before.

**Comment by pickaxe828** [comment] 2021-12-10 12:40
I have the same issue also :0

**Comment by SupLiCatinG** [comment] 2021-12-10 12:50
> Same for me, audio also stops after 6 seconds of playing. I think it began yesterday or day before.

Yeah bean yesterday but i cant play song with spotify connect.

BTW i tried in windows there is a spotify-adblock issue maybe spotify changed url's ?

**Comment by karelo911** [comment] 2021-12-10 13:51
Same issue I'm facing.

**Comment by AnanthVivekanand** [comment] 2021-12-10 15:22
I'm looking into this, I noticed the same problem yesterday. I'll try to get a fix out this weekend if I can find one. Likely, the block/allow list just needs to be updated.

**Comment by SupLiCatinG** [comment] 2021-12-10 16:25
> 

When song ends spotify starts station but this feature doesnt work with spotify-adblock can this issue solveable too ? 
It says cannot fetch url:station error 500

**Comment by p6002** [comment] 2021-12-10 18:14
Same here. Before forks good.

**Comment by CharlieS1103** [comment] 2021-12-10 23:49
@AnanthVivekanand Seems like this might be the cause
<img width="727" alt="Screen Shot 2021-12-10 at 6 48 42 PM" src="https://user-images.githubusercontent.com/60494758/145654799-26d38c67-9418-4051-8f3a-de78c94b0f4b.png">
?

**Comment by CharlieS1103** [comment] 2021-12-10 23:49
https://spclient.wg.spotify.com/playlistextender/extendp/

**Comment by AnanthVivekanand** [comment] 2021-12-11 06:45
I think I solved the issue by proxying through all requests on port 4070. I've been listening for about an hour now with no ads.

 Can everyone try the branch [`greyed-out-fix`](https://github.com/AnanthVivekanand/spotify-adblock/tree/greyed-out-fix)? If there are no ads, I'll merge it into master.

@maximko @karelo911 @pickaxe828 @CharlieS1103 @p6002 @SupLiCatinG

**Comment by karelo911** [comment] 2021-12-11 07:00
@AnanthVivekanand Trying it out. It appears to work fine now.

**Comment by SupLiCatinG** [comment] 2021-12-11 11:16
It is totally fine for me now

**Comment by p6002** [comment] 2021-12-12 09:09
> I solved the issue by proxying through all requests on port 4070

Whats that mean?

**Comment by strejda603** [comment] 2021-12-13 00:10
This branch works great!

**Comment by AnanthVivekanand** [comment] 2021-12-13 00:31
> > I solved the issue by proxying through all requests on port 4070
> 
> Whats that mean?

I noticed requests to made to various IP addresses, not domains, and tested allowing them through (they were previously blocked). I noticed that all of the requests to these IP addresses were on port 4070, so instead of adding them to the whitelist, I added a condition in mitm.js that proxies the request if it occurs on port 4070.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/40674932/145736111-a28d27f7-039c-4720-985f-cf83a32f12e2.png">

**Comment by AnanthVivekanand** [comment] 2021-12-13 00:32
Alright, `greyed-out-fix` has been merged into master, running git pull should pull the changes.

**Closed by AnanthVivekanand** 2021-12-13 00:32 UTC
