### ISSUE TITLE
Missing Script Issue

### ISSUE THREAD

**Issue by hiitsmike** [AnanthVivekanand/spotify-adblock#22] opened 2021-03-02 11:28 UTC
Everything seems to be going smooth until the moment I run "npm start"

From that point, terminal gives me a simple "npm ERR! missing script: start"
I'm unsure what I can do to fix it. Any help would be appreciated!

**Comment by AnanthVivekanand** [comment] 2021-03-23 05:03
Hey, sorry for the late response. Is this still an issue? I just tried out a fresh git clone and it worked fine for me. If you're still having an issue, do you mind posting a screenshot of all your steps and the output?

**Comment by thedough** [comment] 2021-05-10 00:54
![Screenshot 2021-05-10 at 1 54 19 AM](https://user-images.githubusercontent.com/80991661/117593017-a3d41b00-b132-11eb-80cf-03fbb0436490.png)
same issue here

**Comment by AnanthVivekanand** [comment] 2021-05-10 01:08
Not sure why this isn't working, you can just run `node mitm.js` or `node index.js` for now.

**Comment by AnanthVivekanand** [comment] 2021-06-25 02:43
I wasn't able to reproduce this, and I'm pretty sure the issue is just an out-of-date npm installation, so I'll close the issue. Reopen if updating NPM doesn't fix this.

**Closed by AnanthVivekanand** 2021-06-25 02:43 UTC
